### ISSUE TITLE
ghc errors on Ubuntu 14.04.1 LTS

### ISSUE THREAD

**Issue by Y0d0g** [jekor/gressgraph#1]
# ghc -V

The Glorious Glasgow Haskell Compilation System, version 7.6.3
# make

ghc -Wall -package parsec -fglasgow-exts -o gressgraph gressgraph.lhs

on the commandline: Warning:
    -fglasgow-exts is deprecated: Use individual extensions instead
<command line>: cannot satisfy -package parsec
    (use -v for more information)
make: **\* [gressgraph] Error 1

**Comment by XnS** [comment]
<pre>apt-get install libghc-parsec3-dev</pre>

installs the required lib

**Comment by jekor** [comment]
@muellejo: Have you tried installing this via Cabal?

**Comment by Y0d0g** [comment]
@Xns, thanks that works! 
@jekor, i do  not know anything about cabal, but XnS' hint worked.

thanks
