### ISSUE TITLE
Could not find module ‘Prelude’ ‘Data.List’ ‘Text.ParserCombinators.Parsec’

### ISSUE THREAD

**Issue by qwIvan** [jekor/gressgraph#5]
> gressgraph.lhs:33:10: error:
    Could not find module ‘Prelude’
    There are files missing in the ‘base-4.10.1.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
33 | > module Main where
   |          ^^^^

> gressgraph.lhs:34:3:
 error:
    Could not find module ‘Data.List’
    There are files missing in the ‘base-4.10.1.0’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
34 | > import Data.List
   |   ^^^^^^^^^^^^^^^^

> gressgraph.lhs:38:3:
 error:
    Could not find module ‘Text.ParserCombinators.Parsec’
    There are files missing in the ‘parsec-3.1.11’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
38 | > import Text.ParserCombinators.Parsec
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I has already installed `haskell-base` `haskell-base-prelude` `haskell-parsec`

**Comment by jekor** [comment]
Hi Ivan. I haven't compiled gressgraph without the help of Nix in years, and I haven't kept it up to date with the latest GHC and libraries. It will compile if you have Nix installed. You can try running `nix-shell dev.nix` to enter a shell where you should be able to build it with Cabal. Note however that dev.nix references a specific nixpkgs revision from 2015 in order to do this, so it will download and build a lot.

**Comment by curusarn** [comment]
I have the same issue. I'm really hesitant to install a package manager just to get a single program running.

**Comment by rico666** [comment]
I was really hesitant too, but also really desperate.

So after installing god and the world...

`# nix-build dev.nix 
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at /data/proj/gressgraph/dev.nix:2:21
`

I'd say either update it so it at least compiles in 2019 or scrap it.

**Comment by jekor** [comment]
NIX_PATH needs to be set to nixpkgs.

That said, I just compiled this under GHC 8.6.4 without errors, both via `make` (which invokes ghc directly) and via `cabal build`, so I'm not sure where the problem is.

**Comment by jekor** [comment]
If you're seeing this same error, could you please include more information about the build. Are you using Ubuntu/Debian/other system packages, etc?

**Comment by rico666** [comment]
I tried on Arch Linux. As I never used Nix before things like "cabal build" are unknown to me (and would remain so when missing in README).

Unfortunately I removed Nix and gressgraph from my hard disk already because I do not need it anymore, so I cannot provide further feedback.

**Comment by jekor** [comment]
I appreciate the reply and feedback and will look into helping package it for some distros.
